apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-05-12T20:09:50Z"
  generateName: registrations-api-5c8f46685c-
  labels:
    app: registrations-api
    pod-template-hash: 5c8f46685c
  name: registrations-api-5c8f46685c-mhcl8
  namespace: courses
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: registrations-api-5c8f46685c
    uid: 2f640343-0520-41dc-b71f-372cc305c063
  resourceVersion: "14950"
  uid: bfd1238f-eb62-415a-9ca4-5f05f80c66e4
spec:
  containers:
  - env:
    - name: scheduleApiUrl
      value: http://schedule-api-service
    - name: scheduleApiSchedulePath
      value: /schedule/
    - name: MongoDbConnection__ConnectionString
      value: mongodb://root:TokyoJoe138!@mongodb.data.svc.cluster.local:27017/
    - name: MongoDbConnection__Database
      value: registration_db
    - name: MongoDbConnection__Collection
      value: registrations
    - name: MongoDbConnection__LogCommands
      value: "false"
    image: jeffrygonzalez/intro-to-services-may-2022-registrations-api:v0.1
    imagePullPolicy: IfNotPresent
    name: registrations-api
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zf4fg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ml-refvm-594359
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-zf4fg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-05-12T20:09:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-05-12T20:09:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-05-12T20:09:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-05-12T20:09:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://202f6a3221e9e1ef27bc5928500038b2bd439960eb5d4b71d04b8afee41b050b
    image: jeffrygonzalez/intro-to-services-may-2022-registrations-api:v0.1
    imageID: docker://sha256:8f0d9d9e7920d57b57cbe9b0944dea7b6c069ae099dafc662004e1e68f0785eb
    lastState: {}
    name: registrations-api
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-05-12T20:09:52Z"
  hostIP: 172.30.158.89
  phase: Running
  podIP: 10.42.0.92
  podIPs:
  - ip: 10.42.0.92
  qosClass: Guaranteed
  startTime: "2022-05-12T20:09:51Z"
