apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata: 
  name: schedule-api-ingress
  namespace: courses
spec:
  entryPoints:
    - web
  routes: 
    - kind: Rule
      match: Host(`api.rancher.localhost`) && PathPrefix(`/classes/v1`)
      middlewares:
        - name: stripprefix-regex
        - name: cors-promiscuous
      services:
        - kind: Service
          name: schedule-api-service
          port: 80


